//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD_TIPO_SUBPROYECTO
    {
        public int id_Actividad_tipo_subproyecto { get; set; }
        public int id_tipo_actividad { get; set; }
        public Nullable<int> id_tipo_subproyecto { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
