//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCO
    {
        public int id_banco { get; set; }
        public string nombre_banco { get; set; }
        public string cuit_banco { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string pagina_web { get; set; }
        public string nombre_fantasia { get; set; }
        public Nullable<int> id_calle { get; set; }
        public string numero { get; set; }
        public Nullable<int> id_localidad { get; set; }
        public Nullable<int> id_provincia { get; set; }
        public string iva { get; set; }
        public string ingreso_bruto { get; set; }
        public string contacto { get; set; }
    }
}
