//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Prueba_hora
    {
        public int id_hora { get; set; }
        public Nullable<decimal> HoraNormal { get; set; }
        public Nullable<decimal> Hora50 { get; set; }
        public Nullable<decimal> Hora100 { get; set; }
        public Nullable<decimal> HoraNocturna { get; set; }
        public Nullable<decimal> HoraEnfermedad { get; set; }
        public Nullable<decimal> HoraAccidente { get; set; }
        public Nullable<decimal> HoraFeriado { get; set; }
        public Nullable<decimal> HoraNoTrabajada { get; set; }
        public Nullable<decimal> HoraViaje { get; set; }
        public Nullable<decimal> HoraViaje50 { get; set; }
        public Nullable<decimal> HoraViaje100 { get; set; }
    }
}
