//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUES_LIBRADOS
    {
        public int id_cheque_librado { get; set; }
        public string detalle { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> banco_cheque { get; set; }
        public string numero_cheque { get; set; }
        public Nullable<System.DateTime> fecha_librado { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<System.DateTime> periodo { get; set; }
        public Nullable<int> id_cuenta { get; set; }
        public Nullable<int> id_chequera { get; set; }
        public Nullable<bool> control { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<bool> anulado { get; set; }
        public Nullable<bool> archivado { get; set; }
    }
}
