//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int id_contacto { get; set; }
        public string nombre_contacto { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string cargo { get; set; }
        public string departamento { get; set; }
        public string jefe { get; set; }
        public string oficina { get; set; }
        public string asistente { get; set; }
        public string profesion { get; set; }
        public string sobrenombre { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_aniversario { get; set; }
        public string web { get; set; }
        public string detalle { get; set; }
    }
}
