//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuerpo_movimiento_voz
    {
        public int id_cuerpo_movimiento_voz { get; set; }
        public int id_voz { get; set; }
        public Nullable<bool> nc1 { get; set; }
        public Nullable<bool> ok1 { get; set; }
        public Nullable<bool> corresponde1 { get; set; }
        public Nullable<bool> conforme1 { get; set; }
        public Nullable<bool> no_conforme1 { get; set; }
        public string tipo1 { get; set; }
        public string detalle1 { get; set; }
        public Nullable<bool> correccion1 { get; set; }
        public Nullable<int> id_movimiento_voz { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<bool> corresponde2 { get; set; }
        public Nullable<bool> conforme2 { get; set; }
        public Nullable<bool> no_conforme2 { get; set; }
        public string tipo2 { get; set; }
        public string detalle2 { get; set; }
        public Nullable<bool> correccion2 { get; set; }
        public Nullable<decimal> random { get; set; }
        public Nullable<bool> completado { get; set; }
        public Nullable<bool> completado_pm { get; set; }
        public Nullable<bool> control1 { get; set; }
        public Nullable<bool> control2 { get; set; }
        public Nullable<bool> control3 { get; set; }
        public Nullable<bool> pedido_segundo_control { get; set; }
        public Nullable<decimal> numero_revision { get; set; }
        public Nullable<bool> corresponde { get; set; }
    }
}
