//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuerpo_presupuesto
    {
        public int id_cuerpo_presupuesto { get; set; }
        public Nullable<int> id_presupuesto { get; set; }
        public string item { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<decimal> importe { get; set; }
    }
}
