//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUERPO_FACTURA_PROVEEDOR
    {
        public int id_cuerpo_factura_proveedor { get; set; }
        public Nullable<int> id_factura_proveedor { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> alicuota { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> impuesto_interno { get; set; }
        public Nullable<decimal> pack { get; set; }
        public Nullable<bool> tilde { get; set; }
    }
}
