//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_renglon
    {
        public int id_empleado_renglon { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_renglon { get; set; }
    }
}
