//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excepcion_Calendario
    {
        public int id_exception_calendario { get; set; }
        public Nullable<int> id_calendario_laboral { get; set; }
        public Nullable<bool> laborable { get; set; }
        public Nullable<System.DateTime> fecha_comienzo { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> patron_repeticion { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_1 { get; set; }
        public Nullable<System.TimeSpan> hora_fin_1 { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_2 { get; set; }
        public Nullable<System.TimeSpan> hora_fin_2 { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_3 { get; set; }
        public Nullable<System.TimeSpan> hora_fin_3 { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_4 { get; set; }
        public Nullable<System.TimeSpan> hora_fin_4 { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_5 { get; set; }
        public Nullable<System.TimeSpan> hora_fin_5 { get; set; }
        public string nombre_excepcion { get; set; }
        public Nullable<int> freq_type { get; set; }
        public Nullable<int> freq_interval { get; set; }
        public Nullable<int> freq_subday_type { get; set; }
        public Nullable<int> freq_subday_interval { get; set; }
        public Nullable<int> freq_relative_interval { get; set; }
        public Nullable<int> freq_recurrence_factor { get; set; }
    }
}
