//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_recibo_proveedor
    {
        public int id_factura_recibo_proveedor { get; set; }
        public Nullable<int> id_factura_proveedor { get; set; }
        public Nullable<int> id_recibo_proveedor { get; set; }
        public Nullable<decimal> importe_pagado { get; set; }
        public Nullable<bool> efectivo { get; set; }
    }
}
