//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iva_compra_temp
    {
        public int id_iva_compra_temp { get; set; }
        public string numero { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string factura { get; set; }
        public string nombre { get; set; }
        public string cuit { get; set; }
        public Nullable<decimal> imp_gravado { get; set; }
        public Nullable<decimal> imp_exento { get; set; }
        public Nullable<decimal> conc_no_grav { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> imp_otro { get; set; }
        public Nullable<decimal> totals { get; set; }
        public Nullable<decimal> iva_ret { get; set; }
    }
}
