//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int id_libro { get; set; }
        public string numero_asiento { get; set; }
        public string detalle_asiento { get; set; }
        public Nullable<System.DateTime> fecha_asiento { get; set; }
        public Nullable<int> id_cuenta_imputable { get; set; }
        public Nullable<decimal> debe { get; set; }
        public Nullable<decimal> haber { get; set; }
        public string estado { get; set; }
    }
}
