//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIDAD
    {
        public int id_localidad { get; set; }
        public string nombre_localidad { get; set; }
        public Nullable<int> id_provincia { get; set; }
        public string codigo_postal { get; set; }
        public string caracteristica_telefonica { get; set; }
    }
}
