//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public int id_moneda { get; set; }
        public string simbolo { get; set; }
        public string nombre_moneda { get; set; }
        public string abreviatura { get; set; }
    }
}
