//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_voz
    {
        public int id_movimiento_voz { get; set; }
        public Nullable<int> id_control { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ot { get; set; }
        public Nullable<int> id_actividad_proyecto { get; set; }
        public Nullable<int> id_cadista { get; set; }
        public Nullable<int> id_proyect_manager { get; set; }
        public Nullable<int> id_controlador_1 { get; set; }
        public Nullable<int> id_controlador_2 { get; set; }
        public Nullable<bool> completado { get; set; }
        public Nullable<int> id_usuario_anterior { get; set; }
        public Nullable<int> id_controlador_asignado { get; set; }
        public Nullable<bool> pedido_segundo_control { get; set; }
        public Nullable<bool> control_prod { get; set; }
        public Nullable<bool> control_1 { get; set; }
        public Nullable<bool> control_corr_1 { get; set; }
        public Nullable<bool> control_prod_2 { get; set; }
        public Nullable<bool> control_2 { get; set; }
        public Nullable<bool> control_corr_2 { get; set; }
        public Nullable<int> id_usuario_1 { get; set; }
        public Nullable<int> id_usuario_2 { get; set; }
        public Nullable<int> id_usuario_3 { get; set; }
        public Nullable<int> id_usuario_4 { get; set; }
        public Nullable<int> id_usuario_5 { get; set; }
        public Nullable<int> id_usuario_6 { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_completado { get; set; }
        public Nullable<bool> anulado { get; set; }
    }
}
