//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nivel2
    {
        public int id_nivel2 { get; set; }
        public string nombre_nivel2 { get; set; }
        public Nullable<decimal> saldo_nivel2 { get; set; }
        public Nullable<int> id_nivel1 { get; set; }
        public string codigo2 { get; set; }
    }
}
