//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_proveedor
    {
        public int id_pago_proveedor { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> pago { get; set; }
        public string numero_remito { get; set; }
        public string detalle { get; set; }
        public Nullable<bool> efectivo { get; set; }
    }
}
