//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precedencia
    {
        public int id_precedencia { get; set; }
        public string nombre_precedencia { get; set; }
        public Nullable<int> id_actividad_proyecto { get; set; }
        public Nullable<int> id_actividad_proyecto_precedente { get; set; }
        public Nullable<System.DateTime> fecha_precedencia { get; set; }
        public Nullable<decimal> cantidad_hora { get; set; }
        public Nullable<decimal> avance { get; set; }
    }
}
