//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public string abreviatura { get; set; }
        public string ubicacion { get; set; }
        public Nullable<decimal> pack { get; set; }
        public Nullable<decimal> stock_ideal { get; set; }
        public Nullable<decimal> stock_minimo { get; set; }
        public Nullable<decimal> cantidad_compra { get; set; }
        public Nullable<decimal> cantidad_ingreso { get; set; }
        public Nullable<int> id_subtipo_producto { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_unidad { get; set; }
        public Nullable<bool> tilde { get; set; }
        public string tipo_venta { get; set; }
    }
}
