//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacion_Actividad
    {
        public int id_programacion_actividad { get; set; }
        public string nombre_programacion { get; set; }
        public int id_actividad_proyecto { get; set; }
        public Nullable<int> freq_type { get; set; }
        public Nullable<int> freq_interval { get; set; }
        public Nullable<int> freq_relative_interval { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    
        public virtual Actividad_proyecto Actividad_proyecto { get; set; }
    }
}
