//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public int id_proveedor { get; set; }
        public string nombre_proveedor { get; set; }
        public string contacto { get; set; }
        public string cuit { get; set; }
        public string ingreso_bruto { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public Nullable<int> id_condicion_iva { get; set; }
        public Nullable<int> id_tipo_proveedor { get; set; }
    }
}
