//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo_cliente_ingreso_efectivo
    {
        public int id_Recibo_cliente_ingreso_efectivo { get; set; }
        public Nullable<int> id_pago_cliente { get; set; }
        public Nullable<int> id_ingreso_efectivo { get; set; }
        public Nullable<decimal> importe_pagado { get; set; }
    }
}
