//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        public int id_remito { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<System.DateTime> fecha_remito { get; set; }
        public string numero_remito { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string observacion { get; set; }
        public Nullable<int> id_condicion_venta { get; set; }
        public Nullable<int> id_usuario { get; set; }
    }
}
