//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renglon
    {
        public int id_renglon { get; set; }
        public string nombre_renglon { get; set; }
        public string codigo { get; set; }
        public Nullable<bool> mensual { get; set; }
        public Nullable<int> id_tipo_renglon { get; set; }
        public string descripcion { get; set; }
    }
}
