//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_CUENTA_CAJA_2
    {
        public int id_resumen_cuenta_caja { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public string detalle { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_empresa { get; set; }
        public decimal saldo { get; set; }
        public Nullable<int> id_banco { get; set; }
        public Nullable<int> id_cuenta { get; set; }
    }
}
