//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumen_cliente
    {
        public int id_resumen_cliente { get; set; }
        public Nullable<decimal> debe_cliente { get; set; }
        public Nullable<decimal> haber_cliente { get; set; }
        public string detalle_cliente { get; set; }
        public Nullable<System.DateTime> fecha_cliente { get; set; }
        public Nullable<decimal> saldo_cliente { get; set; }
    }
}
