//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldo_cliente
    {
        public int id_saldo_cliente { get; set; }
        public Nullable<System.DateTime> fecha_saldo_cliente { get; set; }
        public Nullable<decimal> saldo_cliente1 { get; set; }
        public int id_cliente { get; set; }
    }
}
