//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDO
    {
        public int id_saldo { get; set; }
        public int id_empresa { get; set; }
        public System.DateTime fecha_saldo { get; set; }
        public decimal saldo1 { get; set; }
        public decimal saldo_libre { get; set; }
        public decimal utilizado { get; set; }
        public decimal otro { get; set; }
        public string detalle { get; set; }
        public decimal decreto_730 { get; set; }
        public decimal combustible { get; set; }
        public Nullable<int> bandera { get; set; }
    }
}
