//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sereno
    {
        public int id_sereno { get; set; }
        public Nullable<decimal> sueldo_sereno { get; set; }
        public Nullable<decimal> contribucion_extraordinaria { get; set; }
        public Nullable<decimal> aporte_solidario { get; set; }
        public Nullable<decimal> ayuda_escolar { get; set; }
        public Nullable<decimal> valor_discapacitado { get; set; }
        public Nullable<decimal> hora_administrativo { get; set; }
        public Nullable<decimal> valor_embargo { get; set; }
    }
}
