//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id_stock { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_almacen { get; set; }
        public Nullable<decimal> stock1 { get; set; }
        public Nullable<bool> actualizado { get; set; }
        public Nullable<decimal> stock_oferta { get; set; }
    }
}
