//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp1
    {
        public int id_temp1 { get; set; }
        public string legajo { get; set; }
        public string nombre_empleado { get; set; }
        public Nullable<decimal> normal { get; set; }
        public Nullable<decimal> extra_50 { get; set; }
        public Nullable<decimal> extra_100 { get; set; }
        public Nullable<decimal> normal_30 { get; set; }
        public Nullable<decimal> extra_50_30 { get; set; }
        public Nullable<decimal> extra_100_30 { get; set; }
        public Nullable<decimal> nocturna { get; set; }
        public Nullable<decimal> enfermedad { get; set; }
        public Nullable<decimal> accidente { get; set; }
        public Nullable<decimal> feriado { get; set; }
        public Nullable<decimal> especial { get; set; }
    }
}
