//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_actividad_proyecto
    {
        public int id_temp_actividad_proyecto { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<int> id_actividad_proyecto { get; set; }
        public Nullable<int> id_usuario { get; set; }
    }
}
