//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_actividad
    {
        public int id_tipo_actividad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> criticidad { get; set; }
        public Nullable<int> porcentaje { get; set; }
        public int logueo_habilitado { get; set; }
        public bool asignable { get; set; }
        public Nullable<decimal> porc_eficiencia { get; set; }
    }
}
