//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD
    {
        public int id_unidad { get; set; }
        public string nombre_unidad { get; set; }
        public string abreviatura { get; set; }
        public Nullable<bool> tilde { get; set; }
    }
}
