//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string password_usuario { get; set; }
        public Nullable<int> id_grupo_usuario { get; set; }
        public string legajo { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> session_activa { get; set; }
        public bool activo { get; set; }
        public Nullable<int> id_calendario_laboral { get; set; }
    
        public virtual Calendario_Laboral Calendario_Laboral { get; set; }

        public String FullName { get { return nombre + " " + apellido; } }
    }
}
