//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voz
    {
        public int id_voz { get; set; }
        public string nombre_voz { get; set; }
        public string icono { get; set; }
        public string codigo { get; set; }
        public string codigo_2 { get; set; }
        public Nullable<decimal> ponderacion { get; set; }
        public Nullable<decimal> random { get; set; }
        public Nullable<bool> corresp { get; set; }
        public Nullable<bool> pond_manual { get; set; }
        public Nullable<int> rango { get; set; }
        public decimal ponderacion_por_rango { get; set; }
    }
}
