//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voz_tipo_voz
    {
        public int id_voz_tipo_voz { get; set; }
        public Nullable<int> id_voz { get; set; }
        public Nullable<int> id_tipo_voz { get; set; }
        public Nullable<decimal> porcentaje_voz { get; set; }
        public Nullable<decimal> porcentaje_tipo_voz { get; set; }
        public Nullable<int> indice { get; set; }
        public Nullable<int> nro { get; set; }
    }
}
