'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Actividad() As DbSet(Of Actividad)
    Public Property Actividad_proyecto() As DbSet(Of Actividad_proyecto)
    Public Property Calle() As DbSet(Of Calle)
    Public Property Cliente() As DbSet(Of Cliente)
    Public Property Cuerpo_movimiento_hora() As DbSet(Of Cuerpo_movimiento_hora)
    Public Property Cuerpo_movimiento_voz() As DbSet(Of Cuerpo_movimiento_voz)
    Public Property DEPARTAMENTO() As DbSet(Of DEPARTAMENTO)
    Public Property Empleado() As DbSet(Of Empleado)
    Public Property Empleado_renglon() As DbSet(Of Empleado_renglon)
    Public Property ITEM() As DbSet(Of ITEM)
    Public Property LOCALIDAD() As DbSet(Of LOCALIDAD)
    Public Property Persona() As DbSet(Of Persona)
    Public Property PRODUCTO() As DbSet(Of PRODUCTO)
    Public Property PROVEEDOR() As DbSet(Of PROVEEDOR)
    Public Property PROVINCIA() As DbSet(Of PROVINCIA)
    Public Property Proyecto() As DbSet(Of Proyecto)
    Public Property Tipo_actividad() As DbSet(Of Tipo_actividad)
    Public Property Tipo_empleado() As DbSet(Of Tipo_empleado)
    Public Property Tipo_proveedor() As DbSet(Of Tipo_proveedor)
    Public Property Tipo_voz() As DbSet(Of Tipo_voz)
    Public Property TRANSFERENCIAS_BANCARIAS() As DbSet(Of TRANSFERENCIAS_BANCARIAS)
    Public Property UNIDAD() As DbSet(Of UNIDAD)
    Public Property USUARIO() As DbSet(Of USUARIO)
    Public Property USUARIO_PERMISO() As DbSet(Of USUARIO_PERMISO)
    Public Property Versionado() As DbSet(Of Versionado)
    Public Property Voz() As DbSet(Of Voz)
    Public Property Voz_tipo_voz() As DbSet(Of Voz_tipo_voz)

End Class
